# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider :virtualbox do |v|
    v.memory = 1512
    v.cpus = 1
  end

  boxes = [
    {
      :name => "web",
      :ip => "192.168.0.110"
    },
    {
      :name => "log",
      :ip => "192.168.0.115"
    }
  ]

  boxes.each do |opts|
    config.vm.define opts [:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "public_network", ip: opts[:ip]
    end
  end
end
