Vagrant.configure(2) do |config|
 config.vm.box = "bento/ubuntu-16.04"
 config.vm.provider "virtualbox" do |v|
   v.memory = 1024
   v.cpus = 1
 end
 config.vm.define "systemd" do |systemd|
  systemd.vm.network "public_network"
  systemd.vm.hostname = "systemd"
  systemd.vm.provision "shell", path: "script.sh"
 end
end
