Vagrant.configure(2) do |config|
 config.vm.box = "almalinux/9"
 config.vm.provider "virtualbox" do |v|
   v.memory = 2048
   v.cpus = 1
 end
 config.vm.define "rpm" do |rpm|
  rpm.vm.network "public_network"
  rpm.vm.hostname = "rpm"
 end
end
