Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "disksubsytem"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "disksubsystem"
  config.vm.network "public_network", ip: "192.168.0.100"
  (0..4).each do |i|
      config.vm.disk :disk, size: "1GB", name: "disk-#{i}"
  end
  #config.vm.provision "shell", path: "setup.sh"
end
